extends SceneTree

const M0CombatSimulationScript = preload("res://scripts/m0/M0CombatSimulation.gd")

var failed = false


func _init() -> void:
	var simulation = M0CombatSimulationScript.new()
	_assert(simulation.load_data(), "m0_test_data.json loads")

	if failed:
		quit(1)
		return

	_assert(simulation.get_active_directions(1) == ["east"], "solo uses east only")
	_assert(simulation.get_active_directions(2) == ["north", "east"], "2p uses north/east")
	_assert(simulation.get_active_directions(3) == ["west", "north", "east"], "3p uses west/north/east")
	_assert(simulation.get_active_directions(4) == ["west", "north", "east", "south"], "4p uses all directions")
	_assert(simulation.get_front_pressure(2).size() == 2, "front pressure follows active direction count")
	_assert(simulation.get_front_pressure_summary(2).contains("north clear"), "front pressure summary marks clear fronts")
	_assert(simulation.describe_wave(1, 10).contains("boss m0_colossus"), "boss wave is described on round 10")
	_assert(simulation.get_enemy_mix_summary(1) == "Walker", "round one enemy mix starts simple")
	_assert(simulation.get_enemy_mix_summary(2).contains("Skitter"), "round two enemy mix adds skitters")
	_assert(simulation.get_enemy_mix_summary(3).contains("Breaker"), "round three enemy mix adds breakers")
	_assert(simulation.get_enemy_mix_summary(4).contains("Bulwark"), "round four enemy mix adds bulwarks")
	_assert(int(simulation.get_enemy_data("m0_skitter").get("hp", 0)) == 4, "skitter enemy data is loaded")
	_assert(int(simulation.get_enemy_data("m0_skitter").get("moveSteps", 0)) == 2, "skitter fast move data is loaded")
	_assert(int(simulation.get_enemy_data("m0_breaker").get("structureDamage", 0)) == 7, "breaker pressure data is loaded")
	_assert(bool(simulation.get_enemy_data("m0_breaker").get("structurePriority", false)), "breaker priority data is loaded")
	_assert(int(simulation.get_enemy_data("m0_bulwark").get("hp", 0)) == 12, "bulwark enemy data is loaded")
	_assert(int(simulation.get_enemy_data("m0_bulwark").get("damageReduction", 0)) == 1, "bulwark armor data is loaded")
	_assert(simulation.get_enemy_trait_summary("m0_skitter").contains("Fast"), "enemy trait summary marks fast enemies")
	_assert(simulation.get_enemy_mix_trait_summary(4).contains("Armor"), "enemy mix trait summary marks armored enemies")
	_assert(simulation.get_autoplay_class_ids() == ["guardian", "architect", "elementalist", "tinkerer"], "autoplay class order is loaded")
	_assert(simulation.get_class_label("guardian") == "Guardian", "guardian class label is loaded")
	_assert(str(simulation.get_class_autoplay_profile("architect").get("tilePlan", "")) == "maze_grid", "architect autoplay plan is loaded")
	_assert(int(simulation.get_class_effects("guardian").get("thornsDamage", 0)) == 1, "guardian effect data is loaded")
	_assert(int(simulation.get_class_effects("guardian").get("tauntPriority", 0)) == 100, "guardian taunt priority data is loaded")
	_assert(int(simulation.get_class_effects("architect").get("barricadeDeathDamage", 0)) == 2, "architect effect data is loaded")
	var setup_report = simulation.get_run_setup_report(3, "elementalist")
	_assert(bool(setup_report.get("ok", false)), "run setup report accepts a valid setup")
	_assert(int(setup_report.get("player_count", 0)) == 3, "run setup report stores player count")
	_assert(str(setup_report.get("class_label", "")) == "Elementalist", "run setup report stores lead class")
	_assert(str(setup_report.get("summary", "")).contains("west, north, east"), "run setup report summarizes active fronts")
	_assert(simulation.get_run_setup_summary(1, "guardian").contains("Guardian"), "run setup summary includes selected class")
	var missing_setup_report = simulation.get_run_setup_report(2, "missing_class")
	_assert(str(missing_setup_report.get("reason", "")) == "unknown_class", "run setup rejects unknown class")
	_assert(str(simulation.get_card_data("m0_arc_spark").get("kind", "")) == "damage_enemy", "damage card data is loaded")
	_assert(str(simulation.get_card_data("m0_field_patch").get("kind", "")) == "repair_structure", "repair card data is loaded")
	_assert(str(simulation.get_card_data("m0_quick_think").get("kind", "")) == "draw_cards", "draw card data is loaded")
	_assert(simulation.get_card_role("m0_arc_spark") == "Damage", "damage card reward role is described")
	_assert(simulation.get_card_effect_summary("m0_field_patch").contains("Repair 4"), "repair card reward effect is described")
	_assert(simulation.get_card_deck_count("m0_tower_permit") == 2, "starting deck count is reported")
	_assert(simulation.get_card_rarity("m0_arc_spark") == "common", "card rarity is loaded")
	_assert(simulation.get_card_rarity_label("m0_heavy_bolt") == "Rare", "rare card rarity label is described")
	_assert(simulation.get_card_reward_min_round("m0_heavy_bolt") == 5, "rare card reward unlock round is loaded")
	_assert(simulation.get_reward_card_pool(1).has("m0_arc_spark"), "round one reward pool includes common cards")
	_assert(not simulation.get_reward_card_pool(1).has("m0_heavy_bolt"), "round one reward pool locks rare cards")
	_assert(simulation.get_reward_card_pool(5).has("m0_heavy_bolt"), "round five reward pool unlocks rare cards")
	_assert(simulation.get_reward_card_pool_summary(5).contains("rare=2"), "reward pool summary counts rare cards")
	var card_reward_report = simulation.get_card_reward_report("m0_arc_spark")
	_assert(bool(card_reward_report.get("ok", false)), "card reward report is available")
	_assert(str(card_reward_report.get("role", "")) == "Damage", "card reward report includes role")
	_assert(str(card_reward_report.get("effect", "")).contains("Deal 2"), "card reward report includes effect")
	_assert(str(card_reward_report.get("rarity_label", "")) == "Common", "card reward report includes rarity")
	var rare_reward_report = simulation.get_card_reward_report("m0_heavy_bolt")
	_assert(str(rare_reward_report.get("rarity_label", "")) == "Rare", "rare reward report includes rarity")
	_assert(str(rare_reward_report.get("unlock", "")) == "R5+", "rare reward report includes unlock")
	_assert(not bool(rare_reward_report.get("reward_unlocked", true)), "rare reward report marks locked early rewards")
	_assert(str(simulation.get_artifact_data("m0_deep_pockets").get("label", "")) == "Deep Pockets", "artifact data is loaded")
	var seed_core_effects: Dictionary = simulation.get_artifact_data("m0_seed_core").get("effects", {})
	_assert(int(seed_core_effects.get("seedManaBonus", 0)) == 1, "artifact effect data is loaded")
	_assert(simulation.get_artifact_effect_summary("m0_deep_pockets").contains("Max hand +1"), "artifact effect summary describes hand bonus")
	var artifact_reward_report = simulation.get_artifact_reward_report("m0_seed_core")
	_assert(bool(artifact_reward_report.get("ok", false)), "artifact reward report is available")
	_assert(str(artifact_reward_report.get("effect", "")).contains("Seed mana +1"), "artifact reward report includes effect")
	_assert(simulation.get_auto_step_interval() > 0.0, "auto step interval is data-driven")
	_assert(simulation.get_autoplay_rounds() == 2, "autoplay round count is data-driven")
	_assert(simulation.get_autoplay_max_steps_per_round() > 0, "autoplay step budget is data-driven")
	_assert(simulation.get_autoplay_cards_per_round() > 0, "autoplay card budget is data-driven")
	_assert(not simulation.get_show_debug_logs_default(), "debug log default starts collapsed")
	_assert(simulation.get_wave_preview_round_count() == 3, "wave preview round count is data-driven")
	_assert(simulation.get_wave_stack_limit() == 3, "wave stack limit is data-driven")
	_assert(simulation.get_max_rounds() == 100, "max round count is loaded")
	_assert(simulation.get_current_round() == 1, "run starts at round 1")
	_assert(simulation.get_mana() == 4, "seed mana is loaded")
	_assert(simulation.get_gold() == 0, "starting gold is loaded")
	_assert(simulation.get_gold_per_kill() == 1, "gold per kill is loaded")
	_assert(simulation.get_hand().size() == 5, "opening hand is drawn")
	_assert(int(simulation.get_deck_zone_counts().get("total_count", 0)) == 5, "deck zone counts track total deck size")
	_assert(simulation.get_deck_cycle_summary().contains("Deck"), "deck cycle summary is available")
	_assert(simulation.get_boss_shop_round_interval() == 10, "boss shop interval is loaded")
	_assert(simulation.get_shop_deck_removal_offer_count() == 4, "shop deck removal offer count is loaded")
	_assert(simulation.get_shop_deck_removal_limit() == 1, "shop deck removal limit is loaded")
	_assert(simulation.get_shop_deck_removal_gold_cost() == 6, "shop deck removal gold cost is loaded")
	_assert(simulation.get_shop_offer_summary() == "Shop: none", "shop starts empty")
	_assert(simulation.get_discard_charges() == 1, "discard charge is loaded")
	_assert(simulation.get_discard_charge_cap() == 3, "discard charge cap is loaded")
	var initial_outcome: Dictionary = simulation.get_run_outcome_report(1)
	_assert(str(initial_outcome.get("focus", "")) == "stable", "initial outcome report is stable")
	_assert(simulation.get_wave_preview_rows(1).size() == 3, "wave preview exposes configured rows")
	_assert(str(simulation.get_wave_preview_rows(1)[1].get("enemy_traits", "")).contains("Fast"), "wave preview exposes enemy traits")
	_assert(simulation.get_next_wave_preview_summary(1).contains("R1"), "wave preview starts at current setup round")
	_assert(simulation.get_next_wave_preview_summary(1).contains("Walker"), "wave preview includes enemy mix")
	_assert(simulation.get_tutorial_rounds() == 3, "tutorial round count is loaded")

	var tutorial_simulation = M0CombatSimulationScript.new()
	_assert(tutorial_simulation.load_data(), "tutorial hint test data loads")
	var setup_hint = tutorial_simulation.get_tutorial_hint(1)
	_assert(bool(setup_hint.get("visible", false)), "tutorial setup hint is visible")
	_assert(str(setup_hint.get("stage", "")) == "setup", "tutorial starts with setup hint")
	_assert(tutorial_simulation.get_tutorial_summary(1).contains("Build the first kill zone"), "tutorial summary includes setup title")
	_assert(bool(tutorial_simulation.place_structure(Vector2i(15, 10), "tower", 1)["ok"]), "tutorial test tower can be placed")
	var start_hint = tutorial_simulation.get_tutorial_hint(1)
	_assert(str(start_hint.get("stage", "")) == "start_wave", "tutorial moves to start wave after first structure")
	_assert(bool(tutorial_simulation.start_wave(1)["ok"]), "tutorial test wave starts")
	var active_hint = tutorial_simulation.get_tutorial_hint(1)
	_assert(bool(active_hint.get("visible", false)), "tutorial active hint remains visible")
	_assert(int(active_hint.get("step", 0)) == 1, "tutorial active hint stays on round one")
	var tutorial_artifact_events = tutorial_simulation.debug_generate_artifact_offer()
	_assert(not tutorial_artifact_events.is_empty(), "tutorial artifact offer can be generated")
	var artifact_hint = tutorial_simulation.get_tutorial_hint(1)
	_assert(str(artifact_hint.get("stage", "")) == "artifact", "tutorial prioritizes artifact reward")

	var enemy_mix_simulation = M0CombatSimulationScript.new()
	_assert(enemy_mix_simulation.load_data(), "enemy mix test data loads")
	_assert(bool(enemy_mix_simulation.debug_set_round(9)["ok"]), "boss preview test round can be set")
	_assert(enemy_mix_simulation.get_next_wave_preview_summary(1).contains("boss Colossus"), "wave preview marks upcoming boss")
	_assert(bool(enemy_mix_simulation.debug_set_round(4)["ok"]), "enemy mix test round can be set")
	_assert(bool(enemy_mix_simulation.start_wave(1)["ok"]), "enemy mix test wave starts")
	for _mix_step in range(5):
		enemy_mix_simulation.step_wave(1)
	var mixed_enemy_ids = {}
	for enemy in enemy_mix_simulation.debug_get_enemies():
		mixed_enemy_ids[str(enemy.get("enemy_id", ""))] = true
	var enemy_mix_stats = enemy_mix_simulation.get_run_stats()
	var spawned_by_enemy_id: Dictionary = enemy_mix_stats.get("spawned_by_enemy_id", {})
	_assert(mixed_enemy_ids.has("m0_skitter"), "enemy mix spawns skitters")
	_assert(mixed_enemy_ids.has("m0_breaker"), "enemy mix spawns breakers")
	_assert(mixed_enemy_ids.has("m0_bulwark"), "enemy mix spawns bulwarks")
	_assert(int(spawned_by_enemy_id.get("m0_bulwark", 0)) == 1, "enemy mix tracks spawned enemy ids")
	_run_enemy_trait_tests()

	var class_simulation = M0CombatSimulationScript.new()
	_assert(class_simulation.load_data(), "class effect test data loads")
	var guardian_tower_result = class_simulation.place_structure(Vector2i(15, 10), "tower", 1, "guardian")
	_assert(bool(guardian_tower_result["ok"]), "guardian tower can be placed")
	var guardian_tower: Dictionary = class_simulation.get_structure_tiles().get("15,10", {})
	_assert(str(guardian_tower.get("class_id", "")) == "guardian", "structure stores owner class")
	_assert(int(guardian_tower.get("max_hp", 0)) == 16, "guardian tower gains hp bonus")
	var architect_barricade_result = class_simulation.place_structure(Vector2i(18, 10), "barricade", 1, "architect")
	_assert(bool(architect_barricade_result["ok"]), "architect barricade can be placed")
	var architect_barricade: Dictionary = class_simulation.get_structure_tiles().get("18,10", {})
	_assert(int(architect_barricade.get("max_hp", 0)) == 24, "architect barricade gains hp bonus")
	var unknown_class_result = class_simulation.place_structure(Vector2i(14, 10), "tower", 1, "missing_class")
	_assert(str(unknown_class_result["reason"]) == "unknown_class", "unknown class placement is rejected")

	_run_class_effect_trigger_tests()
	_run_card_effect_tests()

	var first_card_id = str(simulation.get_hand()[0])
	var card_preview_result = simulation.can_play_card_at_tile(first_card_id, Vector2i(15, 10), 1)
	_assert(bool(card_preview_result["ok"]), "card can preview a legal placement")

	var card_play_result = simulation.play_card_at_tile(first_card_id, Vector2i(15, 10), 1)
	_assert(bool(card_play_result["ok"]), "card can place a tower")
	_assert(simulation.get_mana() == 2, "card play spends mana")
	_assert(simulation.get_hand().size() == 4, "card play removes a hand card")
	_assert(simulation.get_discard_count() == 1, "card play moves card to discard")

	var second_card_id = str(simulation.get_hand()[0])
	var second_card_result = simulation.play_card_at_tile(second_card_id, Vector2i(14, 10), 1)
	_assert(bool(second_card_result["ok"]), "second card can spend some remaining mana")

	var low_mana_result = simulation.can_play_card_at_tile(str(simulation.get_hand()[0]), Vector2i(18, 10), 1)
	_assert(str(low_mana_result["reason"]) == "not_enough_mana", "card play rejects insufficient mana")

	var tower_target_simulation = M0CombatSimulationScript.new()
	_assert(tower_target_simulation.load_data(), "tower card target test data loads")
	_assert(bool(tower_target_simulation.debug_set_hand(["m0_tower_permit"])["ok"]), "tower card target hand can be set")
	var tower_targets = tower_target_simulation.get_card_target_tiles("m0_tower_permit", 1)
	_assert(bool(tower_targets.get("ok", false)), "tower card target report is available")
	_assert(int(tower_targets.get("valid_count", 0)) > 0, "tower card target report has valid tiles")
	var tower_target_tiles: Dictionary = tower_targets.get("tiles", {})
	var valid_tower_target: Dictionary = tower_target_tiles.get("15,10", {})
	var base_blocked_target: Dictionary = tower_target_tiles.get("9,9", {})
	_assert(bool(valid_tower_target.get("valid", false)), "tower card target marks valid build tile")
	_assert(not bool(base_blocked_target.get("valid", true)), "tower card target blocks base tile")
	_assert(str(base_blocked_target.get("reason", "")) == "base_tile_blocked", "tower card target stores blocked reason")
	_assert(bool(base_blocked_target.get("show_invalid", false)), "tower card target shows important blocked tile")
	_assert(str(tower_targets.get("summary", "")).contains("valid="), "tower card target summary includes valid count")

	var damage_target_simulation = M0CombatSimulationScript.new()
	_assert(damage_target_simulation.load_data(), "damage card target test data loads")
	_assert(bool(damage_target_simulation.debug_set_hand(["m0_arc_spark"])["ok"]), "damage card target hand can be set")
	_assert(bool(damage_target_simulation.debug_spawn_enemy(Vector2i(20, 10), 6, "east")["ok"]), "damage card target enemy can be spawned")
	var damage_target_tiles: Dictionary = damage_target_simulation.get_card_target_tiles("m0_arc_spark", 1).get("tiles", {})
	var enemy_damage_target: Dictionary = damage_target_tiles.get("20,10", {})
	var empty_damage_target: Dictionary = damage_target_tiles.get("19,10", {})
	_assert(bool(enemy_damage_target.get("valid", false)), "damage card target marks enemy tile")
	_assert(str(empty_damage_target.get("reason", "")) == "no_enemy_at_tile", "damage card target rejects empty tile")
	_assert(not bool(empty_damage_target.get("show_invalid", true)), "damage card target keeps empty invalid tiles quiet")

	var repair_target_simulation = M0CombatSimulationScript.new()
	_assert(repair_target_simulation.load_data(), "repair card target test data loads")
	_assert(bool(repair_target_simulation.debug_set_hand(["m0_field_patch"])["ok"]), "repair card target hand can be set")
	_assert(bool(repair_target_simulation.debug_place_structure(Vector2i(18, 10), "tower")["ok"]), "repair card target structure can be placed")
	_assert(bool(repair_target_simulation.debug_spawn_enemy(Vector2i(19, 10), 6, "east")["ok"]), "repair card target enemy can be spawned")
	repair_target_simulation.debug_run_enemy_movement()
	var repair_target_tiles: Dictionary = repair_target_simulation.get_card_target_tiles("m0_field_patch", 1).get("tiles", {})
	var damaged_repair_target: Dictionary = repair_target_tiles.get("18,10", {})
	var empty_repair_target: Dictionary = repair_target_tiles.get("17,10", {})
	_assert(bool(damaged_repair_target.get("valid", false)), "repair card target marks damaged structure")
	_assert(str(empty_repair_target.get("reason", "")) == "no_structure", "repair card target rejects empty tile")

	var discard_result = simulation.discard_card(str(simulation.get_hand()[0]))
	_assert(bool(discard_result["ok"]), "selected card can be discarded for mana")
	_assert(simulation.get_mana() == 2, "discard restores mana")
	_assert(simulation.get_hand().size() == 2, "discard removes a hand card")
	_assert(simulation.get_discard_charges() == 0, "discard consumes its charge")

	var second_discard_result = simulation.discard_card(str(simulation.get_hand()[0]))
	_assert(str(second_discard_result["reason"]) == "discard_unavailable", "extra discard is rejected")

	_assert(not simulation.get_tower_range_cells().is_empty(), "tower range cells are exposed")

	var tower_report = simulation.get_tile_report(Vector2i(15, 10), 1)
	var tower_structure: Dictionary = tower_report["structure"]
	_assert(bool(tower_report["ok"]), "tile report accepts valid tile")
	_assert(str(tower_structure.get("type", "")) == "tower", "tile report includes structure data")
	_assert(bool(tower_report["in_tower_range"]), "tile report marks tower range")

	var entrance_report = simulation.get_tile_report(Vector2i(20, 10), 1)
	_assert(str(entrance_report["entrance_direction"]) == "east", "tile report identifies entrance direction")
	_assert(bool(entrance_report["active_entrance"]), "tile report marks active entrance")
	_assert(bool(entrance_report["on_path"]), "tile report marks active path")
	var entrance_pressure: Dictionary = entrance_report.get("front_pressure", {})
	_assert(str(entrance_pressure.get("summary", "")) == "east clear", "tile report includes entrance front pressure")

	var pressure_simulation = M0CombatSimulationScript.new()
	_assert(pressure_simulation.load_data(), "front pressure test data loads")
	_assert(bool(pressure_simulation.start_wave(2)["ok"]), "front pressure test wave starts")
	pressure_simulation.step_wave(2)
	var pressure_by_direction = pressure_simulation.get_front_pressure_by_direction(2)
	var north_pressure: Dictionary = pressure_by_direction.get("north", {})
	_assert(int(north_pressure.get("enemy_count", 0)) == 1, "front pressure counts spawned enemies by direction")
	_assert(int(north_pressure.get("nearest_steps", -1)) >= 0, "front pressure tracks nearest enemy distance")
	_assert(str(north_pressure.get("severity", "")) != "idle", "front pressure marks occupied fronts")

	var intent_simulation = M0CombatSimulationScript.new()
	_assert(intent_simulation.load_data(), "enemy intent test data loads")
	_assert(bool(intent_simulation.debug_spawn_enemy(Vector2i(20, 10), 6, "east")["ok"]), "enemy intent move enemy is spawned")
	var move_intents = intent_simulation.get_enemy_intents(1)
	_assert(not move_intents.is_empty(), "enemy intent list is exposed")
	_assert(str(move_intents[0].get("action", "")) == "move", "enemy intent predicts movement")
	var move_intent_tile: Dictionary = intent_simulation.get_enemy_intent_tiles(1).get("19,10", {})
	_assert(int(move_intent_tile.get("move_count", 0)) == 1, "enemy intent tiles mark next move")
	_assert(intent_simulation.get_enemy_intent_summary(1).contains("move=1"), "enemy intent summary counts movement")

	var base_intent_simulation = M0CombatSimulationScript.new()
	_assert(base_intent_simulation.load_data(), "base enemy intent test data loads")
	_assert(bool(base_intent_simulation.debug_spawn_enemy(Vector2i(12, 10), 6, "east")["ok"]), "base enemy intent enemy is spawned")
	var base_intent_tiles = base_intent_simulation.get_enemy_intent_tiles(1)
	var base_intent_tile: Dictionary = base_intent_tiles.get("11,10", {})
	_assert(int(base_intent_tile.get("base_count", 0)) == 1, "enemy intent marks imminent base hit")
	var base_tile_report = base_intent_simulation.get_tile_report(Vector2i(11, 10), 1)
	var base_report_intent: Dictionary = base_tile_report.get("enemy_intent", {})
	_assert(not base_report_intent.is_empty(), "tile report includes enemy intent")

	var attack_intent_simulation = M0CombatSimulationScript.new()
	_assert(attack_intent_simulation.load_data(), "attack enemy intent test data loads")
	_assert(bool(attack_intent_simulation.debug_place_structure(Vector2i(18, 10), "tower")["ok"]), "attack enemy intent structure is placed")
	_assert(bool(attack_intent_simulation.debug_spawn_enemy(Vector2i(19, 10), 6, "east")["ok"]), "attack enemy intent enemy is spawned")
	var attack_intents = attack_intent_simulation.get_enemy_intents(1)
	_assert(str(attack_intents[0].get("action", "")) == "attack_structure", "enemy intent predicts structure attack")
	var attack_intent_tile: Dictionary = attack_intent_simulation.get_enemy_intent_tiles(1).get("18,10", {})
	_assert(int(attack_intent_tile.get("attack_count", 0)) == 1, "enemy intent tiles mark structure attack")

	var stack_simulation = M0CombatSimulationScript.new()
	_assert(stack_simulation.load_data(), "wave stack data loads")
	var idle_stack_risk: Dictionary = stack_simulation.get_wave_stack_risk_report(1)
	_assert(str(idle_stack_risk.get("severity", "")) == "idle", "wave stack risk is idle before wave")
	_assert(bool(stack_simulation.start_wave(1)["ok"]), "wave stack base wave starts")
	var stable_stack_risk: Dictionary = stack_simulation.get_wave_stack_risk_report(1)
	_assert(bool(stable_stack_risk.get("can_call", false)), "wave stack risk allows stable call")
	_assert(str(stable_stack_risk.get("severity", "")) == "stable", "wave stack risk starts stable")
	var stack_result = stack_simulation.stack_next_wave(1)
	_assert(bool(stack_result["ok"]), "wave stack calls next wave")
	_assert(int(stack_result.get("round", 0)) == 2, "wave stack pulls round 2")
	var second_stack_result = stack_simulation.stack_next_wave(1)
	_assert(bool(second_stack_result["ok"]), "wave stack calls third wave")
	_assert(int(stack_simulation.get_active_wave_stack_depth()) == 3, "wave stack reaches base limit")
	_assert(stack_simulation.get_discard_charges() == 3, "wave stack accumulates discard charges up to cap")
	var rejected_stack_result = stack_simulation.stack_next_wave(1)
	_assert(str(rejected_stack_result.get("reason", "")) == "stack_limit_reached", "wave stack limit rejects extra wave")
	var blocked_stack_risk: Dictionary = stack_simulation.get_wave_stack_risk_report(1)
	_assert(str(blocked_stack_risk.get("severity", "")) == "blocked", "wave stack risk blocks at stack limit")
	stack_simulation.step_wave(1)
	var stacked_enemies = stack_simulation.debug_get_enemies()
	var stacked_stats = stack_simulation.get_run_stats()
	_assert(stacked_enemies.size() == 3, "stacked wave spawns one enemy per active packet")
	if not stacked_enemies.is_empty():
		_assert(str(stacked_enemies[0].get("direction", "")) == "east", "stacked solo wave keeps east direction")
	_assert(int(stacked_stats.get("wave_stacks", 0)) == 2, "wave stack stat is tracked")
	_assert(int(stacked_stats.get("max_wave_stack_depth", 0)) == 3, "wave stack depth stat is tracked")
	for _stack_step in range(90):
		if not stack_simulation.wave_active:
			break
		stack_simulation.step_wave(1)
	_assert(not stack_simulation.wave_active, "stacked wave group ends")
	_assert(stack_simulation.get_completed_rounds() == 3, "stacked wave completes each pulled round")
	_assert(stack_simulation.get_pending_reward_packet_count() == 3, "stacked wave queues one reward packet per round")
	_assert(stack_simulation.get_reward_offer().size() == 3, "stacked wave presents first reward packet")
	if not stack_simulation.get_reward_offer().is_empty():
		var stacked_first_reward = str(stack_simulation.get_reward_offer()[0])
		_assert(bool(stack_simulation.claim_reward_card(stacked_first_reward)["ok"]), "stacked reward first packet can be claimed")
		_assert(stack_simulation.get_pending_reward_packet_count() == 2, "stacked reward queue advances after claim")

	var vote_simulation = M0CombatSimulationScript.new()
	_assert(vote_simulation.load_data(), "wave stack vote data loads")
	_assert(bool(vote_simulation.start_wave(2)["ok"]), "wave stack vote base wave starts")
	var vote_start_result = vote_simulation.stack_next_wave(2)
	_assert(str(vote_start_result.get("reason", "")) == "vote_started", "two-player stack starts a vote")
	_assert(vote_simulation.has_active_wave_stack_vote(), "two-player stack vote remains active")
	_assert(vote_simulation.get_wave_stack_vote_summary(2).contains("1/2"), "two-player vote summary shows first approval")
	_assert(int(vote_simulation.get_active_wave_stack_depth()) == 1, "two-player vote does not stack before approval")
	var vote_pass_result = vote_simulation.stack_next_wave(2)
	_assert(str(vote_pass_result.get("reason", "")) == "wave_stacked", "two-player second approval stacks wave")
	_assert(int(vote_simulation.get_active_wave_stack_depth()) == 2, "two-player vote stack adds next wave")
	var vote_stats = vote_simulation.get_run_stats()
	_assert(int(vote_stats.get("wave_stack_votes_started", 0)) == 1, "wave stack vote start stat is tracked")
	_assert(int(vote_stats.get("wave_stack_votes_passed", 0)) == 1, "wave stack vote pass stat is tracked")

	var unanimous_vote_simulation = M0CombatSimulationScript.new()
	_assert(unanimous_vote_simulation.load_data(), "critical wave stack vote data loads")
	_assert(bool(unanimous_vote_simulation.start_wave(3)["ok"]), "critical wave stack vote base wave starts")
	_assert(bool(unanimous_vote_simulation.debug_set_base_hp(20)["ok"]), "critical wave stack vote base hp can be lowered")
	var unanimous_start_result = unanimous_vote_simulation.stack_next_wave(3)
	_assert(str(unanimous_start_result.get("reason", "")) == "vote_started", "critical three-player stack starts vote")
	_assert(unanimous_vote_simulation.get_wave_stack_vote_summary(3).contains("1/3"), "critical vote starts at one approval")
	var unanimous_wait_result = unanimous_vote_simulation.stack_next_wave(3)
	_assert(str(unanimous_wait_result.get("reason", "")) == "vote_waiting", "critical vote waits for all players")
	_assert(unanimous_vote_simulation.get_wave_stack_vote_summary(3).contains("2/3"), "critical vote keeps waiting at two approvals")
	var unanimous_pass_result = unanimous_vote_simulation.stack_next_wave(3)
	_assert(str(unanimous_pass_result.get("reason", "")) == "wave_stacked", "critical vote passes only after all players approve")
	_assert(int(unanimous_vote_simulation.get_active_wave_stack_depth()) == 2, "critical vote stack adds next wave after unanimity")

	var hold_vote_simulation = M0CombatSimulationScript.new()
	_assert(hold_vote_simulation.load_data(), "held wave stack vote data loads")
	_assert(bool(hold_vote_simulation.start_wave(2)["ok"]), "held wave stack vote base wave starts")
	_assert(str(hold_vote_simulation.stack_next_wave(2).get("reason", "")) == "vote_started", "held wave stack vote starts")
	var hold_vote_result = hold_vote_simulation.hold_wave_stack_vote()
	_assert(str(hold_vote_result.get("reason", "")) == "vote_held", "wave stack vote can be held")
	_assert(not hold_vote_simulation.has_active_wave_stack_vote(), "held wave stack vote is cleared")
	_assert(int(hold_vote_simulation.get_run_stats().get("wave_stack_votes_held", 0)) == 1, "wave stack vote hold stat is tracked")

	var risky_stack_simulation = M0CombatSimulationScript.new()
	_assert(risky_stack_simulation.load_data(), "risky wave stack data loads")
	_assert(bool(risky_stack_simulation.debug_place_structure(Vector2i(18, 10), "tower")["ok"]), "risky stack test tower is placed")
	_assert(bool(risky_stack_simulation.start_wave(1)["ok"]), "risky stack wave starts")
	_assert(bool(risky_stack_simulation.debug_spawn_enemy(Vector2i(19, 10), 6, "east")["ok"]), "risky stack enemy is spawned")
	risky_stack_simulation.debug_run_enemy_movement()
	var risky_stack_report: Dictionary = risky_stack_simulation.get_wave_stack_risk_report(1)
	_assert(str(risky_stack_report.get("severity", "")) != "stable", "damaged structure raises stack risk")
	_assert(risky_stack_simulation.get_wave_stack_risk_summary(1).contains("damaged_structures"), "stack risk summary includes damaged structures")

	var critical_stack_simulation = M0CombatSimulationScript.new()
	_assert(critical_stack_simulation.load_data(), "critical wave stack data loads")
	_assert(bool(critical_stack_simulation.start_wave(1)["ok"]), "critical stack wave starts")
	_assert(bool(critical_stack_simulation.debug_set_base_hp(20)["ok"]), "critical stack base hp can be lowered")
	var critical_stack_report: Dictionary = critical_stack_simulation.get_wave_stack_risk_report(1)
	_assert(str(critical_stack_report.get("severity", "")) == "critical", "low base hp makes stack critical")

	var boss_wave_simulation = M0CombatSimulationScript.new()
	_assert(boss_wave_simulation.load_data(), "boss wave data loads")
	_assert(bool(boss_wave_simulation.debug_set_round(10)["ok"]), "boss wave test round can be set")
	_assert(bool(boss_wave_simulation.start_wave(1)["ok"]), "boss wave starts")
	boss_wave_simulation.step_wave(1)
	var boss_wave_enemies = boss_wave_simulation.debug_get_enemies()
	var boss_wave_enemy: Dictionary = boss_wave_enemies[0]
	var boss_wave_stats = boss_wave_simulation.get_run_stats()
	var boss_pressure: Dictionary = boss_wave_simulation.get_front_pressure_by_direction(1).get("east", {})
	_assert(str(boss_wave_enemy.get("enemy_id", "")) == "m0_colossus", "round 10 first spawn is boss")
	_assert(bool(boss_wave_enemy.get("boss", false)), "boss enemy instance is marked")
	_assert(int(boss_wave_enemy.get("hp", 0)) == 30, "boss enemy uses boss hp")
	_assert(not boss_wave_simulation.get_boss_enemy_tiles().is_empty(), "boss enemy tiles are exposed")
	_assert(int(boss_wave_stats.get("bosses_spawned", 0)) == 1, "boss spawn stat is tracked")
	_assert(int(boss_pressure.get("boss_count", 0)) == 1, "front pressure counts bosses")
	_assert(str(boss_pressure.get("severity", "")) == "critical", "boss front pressure is critical")

	var boss_attack_simulation = M0CombatSimulationScript.new()
	_assert(boss_attack_simulation.load_data(), "boss attack data loads")
	_assert(bool(boss_attack_simulation.place_structure(Vector2i(18, 10), "tower", 1)["ok"]), "boss attack test tower is placed")
	_assert(bool(boss_attack_simulation.debug_spawn_enemy(Vector2i(19, 10), -1, "east", "m0_colossus")["ok"]), "boss attack test enemy is spawned")
	boss_attack_simulation.debug_run_enemy_movement()
	var boss_damaged_tower: Dictionary = boss_attack_simulation.get_structure_tiles().get("18,10", {})
	_assert(int(boss_damaged_tower.get("hp", 0)) == 4, "boss uses stronger structure damage")

	var boss_siege_simulation = M0CombatSimulationScript.new()
	_assert(boss_siege_simulation.load_data(), "boss siege gaze data loads")
	_assert(bool(boss_siege_simulation.debug_place_structure(Vector2i(18, 9), "tower")["ok"]), "boss siege gaze target tower is placed")
	_assert(bool(boss_siege_simulation.debug_spawn_enemy(Vector2i(20, 10), -1, "east", "m0_colossus")["ok"]), "boss siege gaze enemy is spawned")
	boss_siege_simulation.debug_run_enemy_movement()
	var boss_siege_intents = boss_siege_simulation.get_enemy_intents(1)
	var boss_siege_intent: Dictionary = boss_siege_intents[0]
	var boss_siege_intent_tile: Dictionary = boss_siege_simulation.get_enemy_intent_tiles(1).get("18,9", {})
	_assert(str(boss_siege_intent.get("action", "")) == "boss_siege", "boss siege gaze is predicted before firing")
	_assert(int(boss_siege_intent_tile.get("siege_count", 0)) == 1, "boss siege gaze intent tile is marked")
	boss_siege_simulation.debug_run_enemy_movement()
	var boss_siege_tower: Dictionary = boss_siege_simulation.get_structure_tiles().get("18,9", {})
	var boss_siege_stats = boss_siege_simulation.get_run_stats()
	var boss_siege_enemy: Dictionary = boss_siege_simulation.debug_get_enemies()[0]
	_assert(int(boss_siege_tower.get("hp", 0)) == 10, "boss siege gaze damages target structure")
	_assert(int(boss_siege_stats.get("boss_siege_triggers", 0)) == 1, "boss siege gaze trigger stat is tracked")
	_assert(int(boss_siege_stats.get("boss_siege_damage", 0)) == 2, "boss siege gaze damage stat is tracked")
	_assert(int(boss_siege_enemy.get("siege_gaze_charge", -1)) == 0, "boss siege gaze charge resets after firing")
	_assert(str(boss_siege_simulation.get_recent_event_tiles().get("18,9", "")) == "boss_siege", "boss siege gaze event tile is exposed")

	var outcome_simulation = M0CombatSimulationScript.new()
	_assert(outcome_simulation.load_data(), "outcome report data loads")
	_assert(bool(outcome_simulation.debug_set_base_hp(30)["ok"]), "outcome report base hp can be lowered")
	for _hit_index in range(3):
		_assert(
			bool(outcome_simulation.debug_spawn_enemy(Vector2i(12, 10), 1, "east", "m0_colossus")["ok"]),
			"outcome report boss leak enemy is spawned"
		)
		outcome_simulation.debug_run_enemy_movement()
	var outcome_stats = outcome_simulation.get_run_stats()
	var base_hits_by_direction: Dictionary = outcome_stats.get("base_hits_by_direction", {})
	var boss_hits_by_direction: Dictionary = outcome_stats.get("boss_base_hits_by_direction", {})
	var outcome_report: Dictionary = outcome_simulation.get_run_outcome_report(1)
	_assert(int(base_hits_by_direction.get("east", 0)) == 3, "outcome report tracks east base leaks")
	_assert(int(boss_hits_by_direction.get("east", 0)) == 3, "outcome report tracks east boss leaks")
	_assert(str(outcome_report.get("state", "")) == "failed", "outcome report marks failed run")
	_assert(str(outcome_report.get("focus", "")) == "boss_leak", "outcome report prioritizes boss leak")
	_assert(str(outcome_report.get("primary_direction", "")) == "east", "outcome report uses active solo direction")
	_assert(outcome_simulation.get_run_outcome_summary(1).contains("east"), "outcome summary includes primary direction")

	var boss_pulse_simulation = M0CombatSimulationScript.new()
	_assert(boss_pulse_simulation.load_data(), "boss pulse data loads")
	_assert(bool(boss_pulse_simulation.debug_place_structure(Vector2i(18, 9), "tower")["ok"]), "boss pulse test tower is placed")
	_assert(bool(boss_pulse_simulation.debug_set_hand(["m0_arc_spark"])["ok"]), "boss pulse test hand is set")
	_assert(bool(boss_pulse_simulation.debug_spawn_enemy(Vector2i(18, 10), 16, "east", "m0_colossus")["ok"]), "boss pulse test enemy is spawned")
	var boss_pulse_play = boss_pulse_simulation.play_card_at_tile("m0_arc_spark", Vector2i(18, 10), 1)
	_assert(bool(boss_pulse_play["ok"]), "boss pulse can be triggered by damage")
	var boss_pulse_stats = boss_pulse_simulation.get_run_stats()
	var boss_pulsed_tower: Dictionary = boss_pulse_simulation.get_structure_tiles().get("18,9", {})
	var boss_pulsed_enemy: Dictionary = boss_pulse_simulation.debug_get_enemies()[0]
	_assert(bool(boss_pulsed_enemy.get("phase_triggered", false)), "boss pulse marks phase as triggered")
	_assert(int(boss_pulsed_tower.get("hp", 0)) == 9, "boss pulse damages nearby structure")
	_assert(int(boss_pulse_stats.get("boss_phase_triggers", 0)) == 1, "boss pulse phase trigger is tracked")
	_assert(int(boss_pulse_stats.get("boss_pulse_damage", 0)) == 3, "boss pulse damage is tracked")
	_assert(str(boss_pulse_simulation.get_recent_event_tiles().get("18,9", "")) == "boss_pulse", "boss pulse event tile is exposed")

	var artifact_simulation = M0CombatSimulationScript.new()
	_assert(artifact_simulation.load_data(), "artifact reward data loads")
	var artifact_events = artifact_simulation.debug_generate_artifact_offer()
	_assert(artifact_events.size() > 0, "artifact debug offer emits events")
	_assert(artifact_simulation.get_artifact_offer().size() == 2, "artifact reward offer is generated")
	_assert(artifact_simulation.get_artifact_offer_reports().size() == 2, "artifact reward reports match offered artifacts")
	_assert(artifact_simulation.get_artifact_offer_summary().contains("choose 1"), "artifact offer summary explains the choice")
	var artifact_claim_result = artifact_simulation.claim_artifact("m0_deep_pockets")
	_assert(bool(artifact_claim_result["ok"]), "artifact can be claimed")
	_assert(str(artifact_claim_result.get("effect", "")).contains("Max hand +1"), "claimed artifact returns effect summary")
	_assert(
		int(artifact_claim_result.get("equipped_count_after", 0)) == int(artifact_claim_result.get("equipped_count_before", 0)) + 1,
		"claimed artifact reports the new equipped count"
	)
	_assert(artifact_simulation.get_artifact_offer().is_empty(), "artifact offer clears after claim")
	_assert(artifact_simulation.get_equipped_artifacts().has("m0_deep_pockets"), "claimed artifact is equipped")
	_assert(bool(artifact_simulation.get_artifact_reward_report("m0_deep_pockets").get("equipped", false)), "artifact report marks equipped artifacts")
	_assert(artifact_simulation.get_max_hand_size() == 6, "max hand artifact applies")
	artifact_simulation.debug_generate_artifact_offer()
	_assert(not artifact_simulation.get_artifact_offer().has("m0_deep_pockets"), "equipped artifact is not offered again")
	_assert(bool(artifact_simulation.claim_artifact("m0_seed_core")["ok"]), "second artifact can be claimed")
	artifact_simulation.debug_refill_round_resources()
	_assert(artifact_simulation.get_mana() == 5, "seed mana artifact applies on refill")

	var shop_simulation = M0CombatSimulationScript.new()
	_assert(shop_simulation.load_data(), "shop reward data loads")
	var shop_events = shop_simulation.debug_generate_shop_offer(10)
	var shop_offer_size = shop_simulation.get_shop_offer().size()
	_assert(shop_events.size() > 0, "shop debug offer emits events")
	_assert(
		shop_offer_size > 0 and shop_offer_size <= shop_simulation.get_shop_deck_removal_offer_count(),
		"shop reward offer uses available deck cards up to the configured limit"
	)
	_assert(shop_simulation.get_shop_offer_reports().size() == shop_offer_size, "shop reward reports match offered cards")
	_assert(shop_simulation.get_shop_offer_summary().contains("remove 1"), "shop offer summary explains removal")
	_assert(shop_simulation.has_pending_reward(), "shop offer blocks wave start until resolved")
	_assert(str(shop_simulation.start_wave(1).get("reason", "")) == "reward_pending", "pending shop rejects next wave")
	var shop_card_id = str(shop_simulation.get_shop_offer()[0])
	var shop_report = shop_simulation.get_card_removal_report(shop_card_id)
	_assert(int(shop_report.get("gold_cost", 0)) == shop_simulation.get_shop_deck_removal_gold_cost(), "shop report includes removal price")
	_assert(not bool(shop_report.get("can_remove", true)), "shop report blocks unaffordable removal")
	_assert(str(shop_report.get("reason", "")) == "not_enough_gold", "shop report explains unaffordable removal")
	_assert(str(shop_simulation.remove_shop_card(shop_card_id).get("reason", "")) == "not_enough_gold", "shop removal requires gold")
	_assert(bool(shop_simulation.debug_set_gold(shop_simulation.get_shop_deck_removal_gold_cost())["ok"]), "shop test gold can be set")
	shop_report = shop_simulation.get_card_removal_report(shop_card_id)
	_assert(bool(shop_report.get("can_remove", false)), "shop report marks affordable offered cards removable")
	var shop_deck_count_before = int(shop_simulation.get_deck_zone_counts().get("total_count", 0))
	var shop_gold_before = shop_simulation.get_gold()
	var shop_remove_result = shop_simulation.remove_shop_card(shop_card_id)
	_assert(bool(shop_remove_result["ok"]), "shop card can be removed")
	_assert(shop_simulation.get_gold() == shop_gold_before - shop_simulation.get_shop_deck_removal_gold_cost(), "shop removal spends gold")
	_assert(
		int(shop_simulation.get_deck_zone_counts().get("total_count", 0)) == shop_deck_count_before - 1,
		"shop removal permanently reduces deck size"
	)
	_assert(shop_simulation.get_shop_offer().is_empty(), "shop offer clears after removal")
	_assert(shop_simulation.get_last_shop_summary().contains("last trim"), "last shop summary is visible")
	_assert(int(shop_simulation.get_run_stats().get("shop_cards_removed", 0)) == 1, "shop removal stat is tracked")
	_assert(int(shop_simulation.get_run_stats().get("shop_gold_spent", 0)) == shop_simulation.get_shop_deck_removal_gold_cost(), "shop gold spent stat is tracked")

	var shop_skip_simulation = M0CombatSimulationScript.new()
	_assert(shop_skip_simulation.load_data(), "shop skip data loads")
	shop_skip_simulation.debug_generate_shop_offer(10)
	var shop_skip_result = shop_skip_simulation.skip_shop_offer()
	_assert(bool(shop_skip_result["ok"]), "shop offer can be skipped")
	_assert(shop_skip_simulation.get_shop_offer().is_empty(), "shop skip clears offer")
	_assert(shop_skip_simulation.get_last_shop_summary().contains("skipped"), "shop skip summary is visible")

	var break_simulation = M0CombatSimulationScript.new()
	_assert(break_simulation.load_data(), "blocked path pressure data loads")
	for y in range(21):
		_assert(
			bool(break_simulation.debug_place_structure(Vector2i(12, y), "barricade")["ok"]),
			"debug wall segment can be placed"
		)
	_assert(bool(break_simulation.debug_spawn_enemy(Vector2i(20, 10), 6, "east")["ok"]), "blocked path pressure enemy is spawned")
	var break_events = break_simulation.debug_run_enemy_movement()
	var break_enemies = break_simulation.debug_get_enemies()
	var break_enemy_tile: Vector2i = break_enemies[0]["tile"]
	var break_stats = break_simulation.get_run_stats()
	var saw_break_pressure = false
	for event in break_events:
		if event.contains("pressures blocked path"):
			saw_break_pressure = true
	_assert(break_enemy_tile == Vector2i(19, 10), "blocked path pressure moves enemy toward break target")
	_assert(int(break_stats.get("break_targets_found", 0)) == 1, "blocked path pressure tracks break target choice")
	_assert(int(break_stats.get("break_path_steps", 0)) == 1, "blocked path pressure tracks movement")
	_assert(saw_break_pressure, "blocked path pressure emits a debug event")

	var barricade_result = simulation.place_structure(Vector2i(18, 10), "barricade", 1)
	_assert(bool(barricade_result["ok"]), "barricade can be placed near east lane")

	var remove_result = simulation.remove_structure(Vector2i(18, 10))
	_assert(bool(remove_result["ok"]), "structure can be removed before wave")

	var empty_remove_result = simulation.remove_structure(Vector2i(18, 10))
	_assert(not bool(empty_remove_result["ok"]), "empty tile rejects removal")

	barricade_result = simulation.place_structure(Vector2i(18, 10), "barricade", 1)
	_assert(bool(barricade_result["ok"]), "barricade can be replaced after removal")

	var support_tower_result = simulation.place_structure(Vector2i(16, 9), "tower", 1)
	_assert(bool(support_tower_result["ok"]), "debug tower can reinforce kill zone")

	var blocked_result = simulation.place_structure(Vector2i(10, 10), "tower", 1)
	_assert(not bool(blocked_result["ok"]), "base tile rejects placement")

	var wave_result = simulation.start_wave(1)
	_assert(bool(wave_result["ok"]), "wave starts")
	_assert(simulation.get_active_round() == 1, "active wave tracks round 1")
	_assert(simulation.get_mana() == 4, "round start refills seed mana")
	_assert(simulation.get_discard_charges() == 1, "round start refills discard charge")
	_assert(simulation.get_next_wave_preview_summary(1).contains("R2"), "active wave preview points at the next callable wave")

	var active_wave_card_id = str(simulation.get_hand()[0])
	var active_wave_card_result = simulation.play_card_at_tile(active_wave_card_id, Vector2i(17, 9), 1)
	_assert(bool(active_wave_card_result["ok"]), "card can be played during an active wave")

	var saw_spawn = false
	var saw_attack_or_base_damage = false
	var saw_end = false
	var saw_event_tiles = false
	var saw_kill_reward = false

	for _index in range(80):
		var events = simulation.step_wave(1)
		if not simulation.get_recent_event_tiles().is_empty():
			saw_event_tiles = true
		for event in events:
			if event.contains("spawned"):
				saw_spawn = true
			if event.contains("hit") or event.contains("reached base"):
				saw_attack_or_base_damage = true
			if event.contains("Wave complete") or event.contains("Wave group complete") or event.contains("Base destroyed"):
				saw_end = true
			if event.contains("Kill reward"):
				saw_kill_reward = true

		if not simulation.wave_active:
			break

	_assert(saw_spawn, "wave spawns enemies")
	_assert(saw_attack_or_base_damage, "wave produces combat or base damage")
	_assert(saw_event_tiles, "wave exposes recent event tiles")
	_assert(saw_kill_reward, "kills grant resource rewards")
	_assert(saw_end, "wave reaches an end state")
	_assert(simulation.get_completed_rounds() == 1, "round completion is tracked")
	var last_round_report = simulation.get_last_round_report()
	_assert(bool(last_round_report.get("ok", false)), "last round report is available after wave completion")
	_assert(str(last_round_report.get("round_label", "")).contains("round 1"), "last round report stores completed round")
	_assert(int(last_round_report.get("spawned", 0)) > 0, "last round report counts spawned enemies")
	_assert(int(last_round_report.get("reward_packets_queued", 0)) >= 1, "last round report tracks queued rewards")
	_assert(simulation.get_last_round_summary().contains("Last round 1"), "last round summary names the completed round")
	var last_round_panel_report = simulation.get_last_round_panel_report(1)
	_assert(bool(last_round_panel_report.get("ok", false)), "last round panel report is available")
	_assert(str(last_round_panel_report.get("title", "")).contains("round 1"), "last round panel title names the completed round")
	_assert(str(last_round_panel_report.get("reward_line", "")).contains("Reward waiting"), "last round panel reports pending reward")
	_assert(str(last_round_panel_report.get("next_line", "")).contains("R2"), "last round panel previews next wave")
	_assert(simulation.get_last_round_panel_summary(1).contains("Round"), "last round panel summary is formatted")
	_assert(simulation.get_current_round() == 2, "next round is prepared")
	_assert(simulation.get_reward_offer().size() == 3, "wave completion offers card rewards")
	_assert(simulation.get_reward_offer().has("m0_arc_spark"), "rotating rewards can offer effect cards")
	_assert(simulation.get_reward_offer_reports().size() == 3, "reward offer reports match offered cards")
	_assert(simulation.get_reward_offer_summary().contains("choose 1"), "reward offer summary explains the choice")
	var reward_preview = simulation.get_card_reward_report(str(simulation.get_reward_offer()[0]))
	_assert(str(reward_preview.get("claim_preview", "")).contains("discard"), "reward preview explains claim destination")
	_assert(str(reward_preview.get("deck_zone_summary", "")).contains("discard"), "reward preview includes card zone summary")

	var blocked_wave_result = simulation.start_wave(1)
	_assert(str(blocked_wave_result["reason"]) == "reward_pending", "pending reward blocks next wave")

	var reward_card_id = str(simulation.get_reward_offer()[0])
	var discard_count_before_reward = simulation.get_discard_count()
	var claim_reward_result = simulation.claim_reward_card(reward_card_id)
	_assert(bool(claim_reward_result["ok"]), "reward card can be claimed")
	_assert(str(claim_reward_result.get("effect", "")).length() > 0, "claimed reward returns effect summary")
	_assert(
		int(claim_reward_result.get("deck_count_after", 0)) == int(claim_reward_result.get("deck_count_before", 0)) + 1,
		"claimed reward reports the new deck count"
	)
	_assert(str(claim_reward_result.get("destination", "")) == "discard", "claimed reward reports destination pile")
	_assert(str(claim_reward_result.get("deck_after_summary", "")).contains("Deck"), "claimed reward reports full deck summary")
	var last_reward_claim_report = simulation.get_last_reward_claim_report()
	_assert(bool(last_reward_claim_report.get("ok", false)), "last reward claim report is stored")
	_assert(str(last_reward_claim_report.get("card_id", "")) == reward_card_id, "last reward claim report stores card id")
	_assert(simulation.get_last_reward_claim_summary().contains("last pick"), "last reward claim summary is visible")
	_assert(simulation.get_reward_offer().is_empty(), "reward offer clears after claim")
	_assert(simulation.get_reward_offer_summary().contains("last pick"), "empty reward area shows last claimed reward")
	_assert(simulation.get_discard_count() == discard_count_before_reward + 1, "claimed reward enters discard pile")

	var next_wave_result = simulation.start_wave(1)
	_assert(bool(next_wave_result["ok"]), "next wave starts after reward claim")
	_assert(simulation.get_active_round() == 2, "second wave tracks round 2")
	_assert(simulation.get_mana() == 4, "next round refills seed mana")
	_assert(simulation.get_discard_charges() == 1, "next round refills discard charge")

	var stats = simulation.get_run_stats()
	_assert(int(stats.get("spawned", 0)) > 0, "stats count spawned enemies")
	_assert(int(stats.get("steps", 0)) > 0, "stats count wave steps")
	_assert(int(stats.get("cards_drawn", 0)) >= 5, "stats count card draws")
	_assert(int(stats.get("cards_played", 0)) == 3, "stats count played cards")
	_assert(int(stats.get("mana_spent", 0)) == 4, "stats count spent mana")
	_assert(int(stats.get("cards_discarded", 0)) == 1, "stats count discarded cards")
	_assert(int(stats.get("discard_mana_gained", 0)) == 1, "stats count discard mana")
	_assert(int(stats.get("card_rewards_offered", 0)) == 3, "stats count offered reward cards")
	_assert(int(stats.get("card_rewards_taken", 0)) == 1, "stats count claimed reward cards")
	_assert(int(stats.get("rounds_started", 0)) == 2, "stats count started rounds")
	_assert(int(stats.get("rounds_completed", 0)) == 1, "stats count completed rounds")
	_assert(int(stats.get("round_mana_refills", 0)) == 2, "stats count round mana refills")
	_assert(int(stats.get("discard_refills", 0)) == 2, "stats count discard refills")
	_assert(int(stats.get("kill_mana_gained", 0)) > 0, "stats count kill mana rewards")
	_assert(int(stats.get("gold_gained", 0)) > 0, "stats count kill gold rewards")
	_assert(int(stats.get("draw_gauge_gained", 0)) > 0, "stats count draw gauge rewards")
	_assert(
		int(stats.get("tower_hits", 0)) > 0 or int(stats.get("base_hits", 0)) > 0,
		"stats count combat consequences"
	)

	quit(1 if failed else 0)


func _run_enemy_trait_tests() -> void:
	var fast_simulation = M0CombatSimulationScript.new()
	_assert(fast_simulation.load_data(), "fast enemy trait test data loads")
	_assert(bool(fast_simulation.debug_spawn_enemy(Vector2i(20, 10), -1, "east", "m0_skitter")["ok"]), "fast enemy trait test enemy is spawned")
	var fast_trait_tile: Dictionary = fast_simulation.get_enemy_trait_tiles().get("20,10", {})
	_assert(str(fast_trait_tile.get("primary", "")) == "fast", "fast enemy trait tile is marked")
	_assert(str(fast_trait_tile.get("label", "")) == ">", "fast enemy trait tile uses fast marker")
	var fast_tile_report = fast_simulation.get_tile_report(Vector2i(20, 10), 1)
	_assert(str(fast_tile_report.get("enemy_traits", "")).contains("Fast"), "tile report includes fast enemy traits")
	fast_simulation.debug_run_enemy_movement()
	var fast_enemies = fast_simulation.debug_get_enemies()
	var fast_stats = fast_simulation.get_run_stats()
	_assert(not fast_enemies.is_empty(), "fast enemy remains on the field")
	if not fast_enemies.is_empty():
		_assert(fast_enemies[0].get("tile", Vector2i.ZERO) == Vector2i(18, 10), "fast enemy takes a bonus move")
	_assert(int(fast_stats.get("enemy_fast_moves", 0)) == 1, "fast enemy bonus move stat is tracked")

	var breaker_simulation = M0CombatSimulationScript.new()
	_assert(breaker_simulation.load_data(), "breaker trait test data loads")
	_assert(bool(breaker_simulation.debug_place_structure(Vector2i(18, 10), "tower")["ok"]), "breaker trait test structure is placed")
	_assert(bool(breaker_simulation.debug_spawn_enemy(Vector2i(20, 10), -1, "east", "m0_breaker")["ok"]), "breaker trait test enemy is spawned")
	var breaker_trait_tile: Dictionary = breaker_simulation.get_enemy_trait_tiles().get("20,10", {})
	_assert(str(breaker_trait_tile.get("primary", "")) == "breaker", "breaker enemy trait tile is marked")
	_assert(str(breaker_trait_tile.get("label", "")) == "#", "breaker enemy trait tile uses breaker marker")
	var breaker_intents = breaker_simulation.get_enemy_intents(1)
	_assert(str(breaker_intents[0].get("action", "")) == "break_path", "breaker intent prioritizes structure pressure")
	breaker_simulation.debug_run_enemy_movement()
	var breaker_stats = breaker_simulation.get_run_stats()
	_assert(int(breaker_stats.get("enemy_priority_break_moves", 0)) == 1, "breaker priority move stat is tracked")

	var armor_simulation = M0CombatSimulationScript.new()
	_assert(armor_simulation.load_data(), "armor enemy trait test data loads")
	_assert(bool(armor_simulation.debug_set_hand(["m0_arc_spark"])["ok"]), "armor trait test hand is set")
	_assert(bool(armor_simulation.debug_spawn_enemy(Vector2i(18, 10), -1, "east", "m0_bulwark")["ok"]), "armor trait test enemy is spawned")
	var armor_trait_tile: Dictionary = armor_simulation.get_enemy_trait_tiles().get("18,10", {})
	_assert(str(armor_trait_tile.get("primary", "")) == "armor", "armor enemy trait tile is marked")
	_assert(str(armor_trait_tile.get("label", "")) == "A", "armor enemy trait tile uses armor marker")
	var armor_play = armor_simulation.play_card_at_tile("m0_arc_spark", Vector2i(18, 10), 1)
	_assert(bool(armor_play["ok"]), "armor trait damage card can be played")
	var armor_enemy: Dictionary = armor_simulation.debug_get_enemies()[0]
	var armor_stats = armor_simulation.get_run_stats()
	_assert(int(armor_enemy.get("hp", 0)) == 11, "armor enemy reduces incoming damage")
	_assert(int(armor_stats.get("enemy_damage_reduced", 0)) == 1, "armor reduction stat is tracked")
	_assert(int(armor_stats.get("card_damage_dealt", 0)) == 1, "damage stat uses applied armor damage")


func _run_class_effect_trigger_tests() -> void:
	var guardian_simulation = M0CombatSimulationScript.new()
	_assert(guardian_simulation.load_data(), "guardian effect trigger data loads")
	_assert(bool(guardian_simulation.place_structure(Vector2i(18, 10), "tower", 1, "guardian")["ok"]), "guardian test tower is placed")
	_assert(bool(guardian_simulation.debug_spawn_enemy(Vector2i(19, 10), 6)["ok"]), "guardian test enemy is spawned")
	guardian_simulation.debug_run_enemy_movement()
	var guardian_stats = guardian_simulation.get_run_stats()
	var guardian_enemies = guardian_simulation.debug_get_enemies()
	var guardian_enemy_hp = -1
	if not guardian_enemies.is_empty():
		guardian_enemy_hp = int(guardian_enemies[0].get("hp", -1))
	_assert(int(guardian_stats.get("class_thorns_damage", 0)) == 1, "guardian thorns damage is tracked")
	_assert(guardian_enemy_hp == 5, "guardian thorns damages attacker")

	var taunt_simulation = M0CombatSimulationScript.new()
	_assert(taunt_simulation.load_data(), "guardian taunt target data loads")
	_assert(bool(taunt_simulation.place_structure(Vector2i(18, 10), "barricade", 1)["ok"]), "taunt test barricade is placed")
	_assert(bool(taunt_simulation.place_structure(Vector2i(19, 9), "tower", 1, "guardian")["ok"]), "taunt test guardian tower is placed")
	_assert(bool(taunt_simulation.debug_spawn_enemy(Vector2i(19, 10), 6)["ok"]), "taunt test enemy is spawned")
	taunt_simulation.debug_run_enemy_movement()
	var taunt_stats = taunt_simulation.get_run_stats()
	var taunt_structures = taunt_simulation.get_structure_tiles()
	var taunt_barricade: Dictionary = taunt_structures.get("18,10", {})
	var taunt_guardian_tower: Dictionary = taunt_structures.get("19,9", {})
	_assert(int(taunt_stats.get("class_taunt_hits", 0)) == 1, "guardian taunt hit is tracked")
	_assert(int(taunt_barricade.get("hp", 0)) == 20, "guardian taunt leaves adjacent barricade untouched")
	_assert(int(taunt_guardian_tower.get("hp", 0)) == 12, "guardian taunt takes adjacent structure hit")

	var architect_simulation = M0CombatSimulationScript.new()
	_assert(architect_simulation.load_data(), "architect effect trigger data loads")
	_assert(bool(architect_simulation.place_structure(Vector2i(18, 10), "barricade", 1, "architect")["ok"]), "architect test barricade is placed")
	_assert(bool(architect_simulation.debug_spawn_enemy(Vector2i(19, 10), 6)["ok"]), "architect test enemy is spawned")
	for _index in range(6):
		architect_simulation.debug_run_enemy_movement()
	var architect_stats = architect_simulation.get_run_stats()
	_assert(int(architect_stats.get("class_explosion_damage", 0)) == 2, "architect explosion damage is tracked")
	_assert(not architect_simulation.get_structure_tiles().has("18,10"), "architect barricade is destroyed after repeated hits")

	var elementalist_simulation = M0CombatSimulationScript.new()
	_assert(elementalist_simulation.load_data(), "elementalist effect trigger data loads")
	_assert(bool(elementalist_simulation.place_structure(Vector2i(15, 10), "tower", 1, "elementalist")["ok"]), "elementalist test tower is placed")
	_assert(bool(elementalist_simulation.debug_spawn_enemy(Vector2i(18, 10), 6)["ok"]), "elementalist primary enemy is spawned")
	_assert(bool(elementalist_simulation.debug_spawn_enemy(Vector2i(18, 11), 6)["ok"]), "elementalist splash enemy is spawned")
	elementalist_simulation.debug_run_tower_attack()
	var elementalist_stats = elementalist_simulation.get_run_stats()
	var elementalist_enemies = elementalist_simulation.debug_get_enemies()
	var splash_enemy_hp = -1
	for enemy in elementalist_enemies:
		var enemy_tile: Vector2i = enemy["tile"]
		if enemy_tile == Vector2i(18, 11):
			splash_enemy_hp = int(enemy.get("hp", -1))
	_assert(int(elementalist_stats.get("class_splash_damage", 0)) == 1, "elementalist splash damage is tracked")
	_assert(splash_enemy_hp == 5, "elementalist splash damages nearby enemy")

	var tinkerer_aura_simulation = M0CombatSimulationScript.new()
	_assert(tinkerer_aura_simulation.load_data(), "tinkerer aura trigger data loads")
	_assert(bool(tinkerer_aura_simulation.place_structure(Vector2i(15, 10), "tower", 1, "tinkerer")["ok"]), "tinkerer aura test tower is placed")
	_assert(bool(tinkerer_aura_simulation.debug_spawn_enemy(Vector2i(18, 10), 6)["ok"]), "tinkerer aura test enemy is spawned")
	tinkerer_aura_simulation.debug_run_tower_attack()
	var tinkerer_aura_stats = tinkerer_aura_simulation.get_run_stats()
	var aura_enemies = tinkerer_aura_simulation.debug_get_enemies()
	var aura_enemy_hp = -1
	if not aura_enemies.is_empty():
		aura_enemy_hp = int(aura_enemies[0].get("hp", -1))
	_assert(int(tinkerer_aura_stats.get("class_aura_damage", 0)) == 1, "tinkerer aura damage is tracked")
	_assert(aura_enemy_hp == 4, "tinkerer aura increases tower damage")

	var tinkerer_repair_simulation = M0CombatSimulationScript.new()
	_assert(tinkerer_repair_simulation.load_data(), "tinkerer repair trigger data loads")
	_assert(bool(tinkerer_repair_simulation.place_structure(Vector2i(18, 10), "tower", 1, "tinkerer")["ok"]), "tinkerer repair test tower is placed")
	_assert(bool(tinkerer_repair_simulation.debug_spawn_enemy(Vector2i(19, 10), 6)["ok"]), "tinkerer repair test enemy is spawned")
	tinkerer_repair_simulation.debug_run_enemy_movement()
	tinkerer_repair_simulation.debug_refill_round_resources()
	var tinkerer_repair_stats = tinkerer_repair_simulation.get_run_stats()
	var repaired_structure: Dictionary = tinkerer_repair_simulation.get_structure_tiles().get("18,10", {})
	_assert(int(tinkerer_repair_stats.get("class_repairs", 0)) == 2, "tinkerer repair is tracked")
	_assert(int(repaired_structure.get("hp", 0)) == 10, "tinkerer repair restores structure hp")


func _run_card_effect_tests() -> void:
	var damage_simulation = M0CombatSimulationScript.new()
	_assert(damage_simulation.load_data(), "damage card test data loads")
	_assert(bool(damage_simulation.debug_set_hand(["m0_arc_spark"])["ok"]), "damage card test hand is set")
	_assert(bool(damage_simulation.debug_spawn_enemy(Vector2i(18, 10), 6)["ok"]), "damage card target enemy is spawned")
	var damage_preview = damage_simulation.can_play_card_at_tile("m0_arc_spark", Vector2i(18, 10), 1)
	_assert(bool(damage_preview["ok"]), "damage card can target enemy tile")
	var damage_play = damage_simulation.play_card_at_tile("m0_arc_spark", Vector2i(18, 10), 1)
	_assert(bool(damage_play["ok"]), "damage card can be played")
	var damage_stats = damage_simulation.get_run_stats()
	var damaged_enemies = damage_simulation.debug_get_enemies()
	var damaged_enemy_hp = -1
	if not damaged_enemies.is_empty():
		damaged_enemy_hp = int(damaged_enemies[0].get("hp", -1))
	_assert(damaged_enemy_hp == 4, "damage card reduces enemy hp")
	_assert(int(damage_stats.get("card_damage_dealt", 0)) == 2, "damage card stat is tracked")
	_assert(damage_simulation.get_mana() == 3, "damage card spends mana")

	var repair_simulation = M0CombatSimulationScript.new()
	_assert(repair_simulation.load_data(), "repair card test data loads")
	_assert(bool(repair_simulation.place_structure(Vector2i(18, 10), "tower", 1)["ok"]), "repair card test tower is placed")
	_assert(bool(repair_simulation.debug_spawn_enemy(Vector2i(19, 10), 6)["ok"]), "repair card test enemy is spawned")
	repair_simulation.debug_run_enemy_movement()
	_assert(bool(repair_simulation.debug_set_hand(["m0_field_patch"])["ok"]), "repair card test hand is set")
	var repair_preview = repair_simulation.can_play_card_at_tile("m0_field_patch", Vector2i(18, 10), 1)
	_assert(bool(repair_preview["ok"]), "repair card can target damaged structure")
	var repair_play = repair_simulation.play_card_at_tile("m0_field_patch", Vector2i(18, 10), 1)
	_assert(bool(repair_play["ok"]), "repair card can be played")
	var repair_stats = repair_simulation.get_run_stats()
	var repaired_structure: Dictionary = repair_simulation.get_structure_tiles().get("18,10", {})
	_assert(int(repaired_structure.get("hp", 0)) == 12, "repair card restores structure hp")
	_assert(int(repair_stats.get("card_repairs", 0)) == 4, "repair card stat is tracked")

	var draw_simulation = M0CombatSimulationScript.new()
	_assert(draw_simulation.load_data(), "draw card test data loads")
	_assert(bool(draw_simulation.debug_set_hand(["m0_quick_think"])["ok"]), "draw card test hand is set")
	_assert(bool(draw_simulation.debug_set_draw_pile(["m0_tower_permit"])["ok"]), "draw card test draw pile is set")
	var draw_preview = draw_simulation.can_play_card("m0_quick_think")
	_assert(bool(draw_preview["ok"]), "draw card can be played without tile")
	var draw_play = draw_simulation.play_card("m0_quick_think")
	_assert(bool(draw_play["ok"]), "draw card play succeeds")
	var draw_stats = draw_simulation.get_run_stats()
	var draw_hand = draw_simulation.get_hand()
	_assert(draw_hand.size() == 1 and str(draw_hand[0]) == "m0_tower_permit", "draw card draws from draw pile")
	_assert(int(draw_stats.get("card_effect_draws", 0)) == 1, "draw card stat is tracked")


func _assert(condition: bool, label: String) -> void:
	if condition:
		print("[PASS] %s" % label)
	else:
		failed = true
		push_error("[FAIL] %s" % label)
